[build.environment]
  NODE_VERSION = "20"

[[edge_functions]]
  function = "track-conversions"
  path = "/thankyou"

[[edge_functions]]
  function = "track-utm"
  path = "/*"
  excludedPath=["/thankyou"]