[build.environment]
  NODE_VERSION = "20"
  functions = "functions"

[functions]
  external_node_modules = ["node-fetch", "stripe"]
  node_bundler = "esbuild"

[functions."stripe-webhooks"]
  timeout = 30

[[edge_functions]]
  function = "track-conversions"
  path = "/thankyou"

[[edge_functions]]
  function = "track-utm"
  path = "/*"
  excludedPath=[
    "/.netlify/*",
    "/netlify/",
    "/thankyou",
    "/sitemap.xml",
    # "/buy_test",
    "/rulebook",
    "/rulebook.pdf",
    "/favicon.ico",
    "/manifest.json",
    "/robots.txt",
    "/*.css",
    "/*.js",
    "/*.map",
    "/*.png",
    "/*.jpg",
    "/*.jpeg",
    "/*.json",
    "/*.webp",
    "/*.svg",
    "/*.gif",
    "/*.ico",
    "/*.woff",
    "/*.woff2",
    "/*.ttf",
    "/*.otf",
    "/*.pdf",
    "/*.xml",
  ]