import type { DirectionEpisodeData } from "../../types/card.js";

const exampleEpisodes: DirectionEpisodeData[] = [
  { type: "episode", description: "6 a.m. in a government building." },
  { type: "episode", description: "A bank during a robbery." },
  { type: "episode", description: "A beach full of influencers." },
  { type: "episode", description: "A building on fire." },
  { type: "episode", description: "A bus that can shrink at will." },
  { type: "episode", description: "A castle floating in the sky." },
  { type: "episode", description: "A cemetery on a full moon at midnight." },
  {
    type: "episode",
    description: "A club where memories only last one minute.",
  },
  { type: "episode", description: "A comedy show, but the comedian is evil." },
  { type: "episode", description: "A conference for fake magicians." },
  {
    type: "episode",
    description: "A court where you argue in interpretive dance.",
  },
  { type: "episode", description: "A daycare for future geniuses." },
  { type: "episode", description: "A desert filled with sugar not sand." },
  { type: "episode", description: "A factory that builds robots." },
  {
    type: "episode",
    description: "A fancy restaurant where eating is prohibited.",
  },
  { type: "episode", description: "A farm for cloning extinct animals." },
  { type: "episode", description: "A gym for ghosts and zombies." },
  { type: "episode", description: "A hospital for retired superheroes." },
  { type: "episode", description: "A laboratory for experiments gone wrong." },
  { type: "episode", description: "A lecture given by a pickup artist." },
  { type: "episode", description: "A library where books read you instead." },
  {
    type: "episode",
    description: "A meet and greet event for doppelgangers.",
  },
  {
    type: "episode",
    description: "A movie theater that can predict the future.",
  },
  { type: "episode", description: "A museum of invisible art." },
  { type: "episode", description: "A park full of multiplying bunnies." },
  { type: "episode", description: "A runaway train and the power is out." },
  { type: "episode", description: "A school for aspiring villains." },
  { type: "episode", description: "A station for mystical vehicles." },
  { type: "episode", description: "A teleporting bar." },
  { type: "episode", description: "A theme park of illusions." },
  { type: "episode", description: "A travel agency for time travel." },
  { type: "episode", description: "A workshop for procrastinators." },
  { type: "episode", description: "An airplane making a crash landing." },
  { type: "episode", description: "An airport for winged creatures." },
  { type: "episode", description: "An ancient battlefield." },
  { type: "episode", description: "An eating competition for robots." },
  { type: "episode", description: "An office of infinite cubicles." },
  { type: "episode", description: "At a police lineup of suspects." },
  { type: "episode", description: "Deep in an underwater ocean base." },
  { type: "episode", description: "On top of the world's largest mattress." },
  { type: "episode", description: "Santa's attic." },
  { type: "episode", description: "The 'Cloud'." },
  { type: "episode", description: "The basement of a wanted criminal." },
  { type: "episode", description: "The bedroom of an influential leader." },
  { type: "episode", description: "The inside of a board game box." },
  { type: "episode", description: "The inside of a giant human body." },
  { type: "episode", description: "The line for the bathroom at a festival." },
  { type: "episode", description: "The North Pole post global warming." },
  { type: "episode", description: "The woods filled with sentient trees." },
  {
    type: "episode",
    description: "The zoo but all the animals just broke free.",
  },
];

const exampleDirections: DirectionEpisodeData[] = [
  { type: "direction", description: "Announce a new business" },
  { type: "direction", description: "Announce a new religion" },
  { type: "direction", description: "Announce a pregnancy" },
  { type: "direction", description: "Announce an engagement" },
  { type: "direction", description: "Celebrate a birthday" },
  { type: "direction", description: "Celebrate a graduation" },
  { type: "direction", description: "Celebrate a holiday" },
  { type: "direction", description: "Celebrate a promotion" },
  { type: "direction", description: "Celebrate the birth of a child" },
  { type: "direction", description: "Complain about food" },
  { type: "direction", description: "Complain about life" },
  { type: "direction", description: "Complain about politics" },
  { type: "direction", description: "Complain about someone" },
  { type: "direction", description: "Complain about your career" },
  { type: "direction", description: "Complain about your love life" },
  { type: "direction", description: "Cook a meal" },
  { type: "direction", description: "Crack a joke" },
  { type: "direction", description: "Dance" },
  { type: "direction", description: "Film a short video" },
  { type: "direction", description: "Get drunk and cry" },
  { type: "direction", description: "Get drunk and fight" },
  { type: "direction", description: "Give away prized treasure" },
  { type: "direction", description: "Give away unwanted junk" },
  { type: "direction", description: "Invite everyone to your home" },
  { type: "direction", description: "Invite everyone to your workplace" },
  { type: "direction", description: "Make drinks" },
  { type: "direction", description: "Plan a blind date" },
  { type: "direction", description: "Plan a career fair" },
  { type: "direction", description: "Plan a magical party" },
  { type: "direction", description: "Share a controversial opinion" },
  { type: "direction", description: "Share an online article" },
  { type: "direction", description: "Share something confusing" },
  { type: "direction", description: "Share something dark" },
  { type: "direction", description: "Share something inspiring" },
  { type: "direction", description: "Share something magical" },
  { type: "direction", description: "Share something romantic" },
  { type: "direction", description: "Share something tragic" },
  { type: "direction", description: "Share the results of an exam" },
  { type: "direction", description: "Share your feelings" },
  { type: "direction", description: "Show off your body" },
  { type: "direction", description: "Show off your riches" },
  { type: "direction", description: "Show off your skills" },
  { type: "direction", description: "Show off your trophies or awards" },
  { type: "direction", description: "Sing" },
  { type: "direction", description: "Talk about your childhood" },
  { type: "direction", description: "Talk about your dreams" },
  { type: "direction", description: "Talk about your ethnicity or species" },
  { type: "direction", description: "Talk about your family" },
  { type: "direction", description: "Talk about your friends" },
  { type: "direction", description: "Talk about your hobbies" },
  { type: "direction", description: "Attend a LOVE or HATE festival" },
  { type: "direction", description: "Bask in GLORY or FLATULENCE" },
  { type: "direction", description: "Borrow from a PARALLEL or DIGITAL universe" },
  { type: "direction", description: "Build a MURDEROUS or PEACE-LOVING robot" },
  { type: "direction", description: "Buy something USELESS or ADDICTIVE" },
  { type: "direction", description: "Cast a MAGIC SPELL or an ILLEGAL VOTE" },
  { type: "direction", description: "Cause MUSCULAR or AWKWARD tension" },
  { type: "direction", description: "Commit BLASPHEMY or ATROCITY" },
  { type: "direction", description: "Concoct a LOVE or SHAPESHIFTING potion" },
  { type: "direction", description: "Conjure a time VORTEX or PARADOX" },
  { type: "direction", description: "Create something MAGICAL or CURSED" },
  { type: "direction", description: "Dig up a FUTURISTIC or GHOSTLY item" },
  { type: "direction", description: "DONATE or LAUNDER money" },
  { type: "direction", description: "EAT or THROW UP something forbidden" },
  {
    type: "direction",
    description: "Enact INSIDER TRADING or MULTI-LEVEL MARKETING",
  },
  { type: "direction", description: "ENCHANT or CURSE something" },
  { type: "direction", description: "Find an ANGELIC or RADIOACTIVE body" },
  { type: "direction", description: "Give up your ORGANS or DIGNITY" },
  { type: "direction", description: "Ignore your PAIN or DESIRES" },
  { type: "direction", description: "Incite a POLITICAL or VIRTUAL riot" },
  { type: "direction", description: "Inhale toxic GASES or VIBES" },
  { type: "direction", description: "Journey to PARADISE or CHAOS" },
  { type: "direction", description: "Mix two CHEMICALS or SOULS together" },
  { type: "direction", description: "Obtain IMMORTALITY or OMNISCIENCE" },
  { type: "direction", description: "Participate in a BAKE OFF or FIGHT CLUB" },
  { type: "direction", description: "Perform a RITUAL or MIRACLE" },
  { type: "direction", description: "PLANT or DEFUSE a giant bomb" },
  { type: "direction", description: "Purchase a cursed WEAPON or PRINTER" },
  { type: "direction", description: "RAISE or BURY the dead" },
  { type: "direction", description: "Recruit for a CULT or QUEST" },
  { type: "direction", description: "Sign up for FERTILITY or PIRATE school" },
  { type: "direction", description: "SMITE or BLESS someone" },
  { type: "direction", description: "SNITCH ON or SACRIFICE FOR someone" },
  { type: "direction", description: "Spawn a sentient COMPUTER or ANIMAL" },
  { type: "direction", description: "Spread fake NEWS or CURRENCY" },
  { type: "direction", description: "Stage a LAB or SOCIAL experiment" },
  {
    type: "direction",
    description: "Steal a TIME TRAVELLER'S or HYPNOTIST'S watch",
  },
  { type: "direction", description: "Sue someone for PROMISCUITY or DEFAMATION" },
  { type: "direction", description: "Summon a DEMON or an ANGEL" },
  { type: "direction", description: "Swallow COLORFUL or SMELLY pills" },
  { type: "direction", description: "Swap PERSONALITIES or POSSESSIONS" },
  { type: "direction", description: "Swindle money from WORK or FAMILY" },
  { type: "direction", description: "Take an ICE or LAVA bath" },
  { type: "direction", description: "Uncover a GOVERNMENT or ALIEN conspiracy" },
  { type: "direction", description: "Upload your CONSCIOUSNESS or BODY" },
  { type: "direction", description: "Use a CLONING MACHINE or a TELEPORTER" },
  { type: "direction", description: "Vaporize an ENEMY or a FRIEND" },
  {
    type: "direction",
    description: "Violate INTERNATIONAL LAW or SOCIAL ETIQUETTE",
  },
  { type: "direction", description: "Wield a DULL SWORD or a TOXIC PLANT" },
  { type: "direction", description: "Witness divine INTELLIGENCE or INTERVENTION" },
];

//return the details of a random direction or episode, not the same as previous
export function getRandomDirectionEpisode(type: "direction" | "episode", exampleID?: string): DirectionEpisodeData {
  const arrayToSearch = type === "direction" ? exampleDirections : exampleEpisodes;
  const randomCard =
    arrayToSearch[Math.floor(Math.random() * arrayToSearch.length)];

  if (typeof exampleID !== "undefined") {
    return randomCard.description === exampleID
      ? getRandomDirectionEpisode(type, exampleID)
      : randomCard;
  } else {
    return randomCard;
  }
}

//returns X amount of random directions or episodes
export function getRandomDirectionsEpisodes(type: "direction" | "episode", totalCount: number): DirectionEpisodeData[] {
  const arrayToSearch = type === "direction" ? exampleDirections : exampleEpisodes;
  const randomSorted = arrayToSearch.sort(() => (Math.random() > 0.5 ? 1 : -1));
  return randomSorted.slice(0, totalCount);
}
